language: cpp
dist: bionic
compiler: gcc
cache: packages

install: 
  - sudo apt update -qq
  # ImageMagick
  #- sudo add-apt-repository -y ppa:opencpu/imagemagick
  #- sudo apt-get update
  - sudo apt install -qq libmagick++-dev
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt
  - sudo apt install -qq qt5-qmake qt5-default
  # Qwt
  - sudo apt install -qq libqwt-qt5-dev
  # cppcheck
  - sudo apt install -qq cppcheck 
  # sloccount
  - sudo apt install -qq sloccount 
  # Codecov
  - sudo pip install codecov
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check
  # R and ape
  - sudo apt install -qq r-base r-base-dev r-cran-ape r-cran-phangorn r-cran-phytools r-cran-devtools r-cran-desolve libgfortran-8-dev liblapack-dev libblas-dev
  - # Fix libfortran link
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.8 /usr/lib/libgfortran.so
  - sudo Rscript -e 'devtools::install_github("richelbilderbeek/DDD")'
  - sudo Rscript -e 'install.packages("PBD")'
  # OCLint
  - ./scripts/install_oclint

services:
 - xvfb

script: 
  - ./scripts/download_other_githubs
  - qmake -qt=qt5 sado_test.pro
  - make --silent
  - ./sado_test
  - qmake -qt=qt5 sado_gui.pro
  - make --silent
  - ./sado_gui &
  - sleep 10
  - sudo killall -9 sado_gui
  # cppcheck, be mild
  - cppcheck --quiet --error-exitcode=0 . 
  #- cppcheck --quiet --error-exitcode=1 . 
  # Call OCLint
  - ./scripts/do_oclint | true
  # Get code coverage
  #- ./scripts/get_code_cov >/dev/null
  #- codecov >/dev/null
  # Check dead links
  #- rm .travis.yml
  #- ./scripts/check_dead_links || true
  # SLOCcount
  #- cd ..; sloccount --overhead 1 --personcost 22614 $my_github; cd $my_github

after_success:
  - bash <(curl -s https://codecov.io/bash)

