#!/bin/bash

cd ..

if [ ! -d boost_graph_cookbook_1 ]; then
  git clone -b develop https://github.com/richelbilderbeek/boost_graph_cookbook_1
fi

if [ ! -d SurfacePlotter ]; then
  git clone -b develop https://github.com/richelbilderbeek/SurfacePlotter
fi

if [ ! -d gausser ]; then
  git clone -b develop https://github.com/richelbilderbeek/gausser
fi

if [ ! -d RibiLibraries ]; then
  git clone -b develop https://github.com/richelbilderbeek/RibiLibraries
fi
